// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wyvern/data/model/orderDto.proto

package com.company.biz.vo;

public final class OrderVo {
  private OrderVo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serialNo = 1;
    /**
     * <code>required string serialNo = 1;</code>
     */
    boolean hasSerialNo();
    /**
     * <code>required string serialNo = 1;</code>
     */
    java.lang.String getSerialNo();
    /**
     * <code>required string serialNo = 1;</code>
     */
    com.google.protobuf.ByteString
        getSerialNoBytes();

    // optional string orderName = 2;
    /**
     * <code>optional string orderName = 2;</code>
     */
    boolean hasOrderName();
    /**
     * <code>optional string orderName = 2;</code>
     */
    java.lang.String getOrderName();
    /**
     * <code>optional string orderName = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrderNameBytes();

    // repeated .v6.data.model.OrderDetail.Address addressList = 3;
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    java.util.List<com.company.biz.vo.OrderVo.OrderDetail.Address> 
        getAddressListList();
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    com.company.biz.vo.OrderVo.OrderDetail.Address getAddressList(int index);
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    int getAddressListCount();
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    java.util.List<? extends com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder> 
        getAddressListOrBuilderList();
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder getAddressListOrBuilder(
        int index);

    // optional double orderPrice = 4;
    /**
     * <code>optional double orderPrice = 4;</code>
     */
    boolean hasOrderPrice();
    /**
     * <code>optional double orderPrice = 4;</code>
     */
    double getOrderPrice();
  }
  /**
   * Protobuf type {@code v6.data.model.OrderDetail}
   */
  public static final class OrderDetail extends
      com.google.protobuf.GeneratedMessage
      implements OrderDetailOrBuilder {
    // Use OrderDetail.newBuilder() to construct.
    private OrderDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderDetail defaultInstance;
    public static OrderDetail getDefaultInstance() {
      return defaultInstance;
    }

    public OrderDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serialNo_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              orderName_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                addressList_ = new java.util.ArrayList<com.company.biz.vo.OrderVo.OrderDetail.Address>();
                mutable_bitField0_ |= 0x00000004;
              }
              addressList_.add(input.readMessage(com.company.biz.vo.OrderVo.OrderDetail.Address.PARSER, extensionRegistry));
              break;
            }
            case 33: {
              bitField0_ |= 0x00000004;
              orderPrice_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          addressList_ = java.util.Collections.unmodifiableList(addressList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.company.biz.vo.OrderVo.OrderDetail.class, com.company.biz.vo.OrderVo.OrderDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<OrderDetail> PARSER =
        new com.google.protobuf.AbstractParser<OrderDetail>() {
      public OrderDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OrderDetail> getParserForType() {
      return PARSER;
    }

    public interface AddressOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string address = 1;
      /**
       * <code>optional string address = 1;</code>
       */
      boolean hasAddress();
      /**
       * <code>optional string address = 1;</code>
       */
      java.lang.String getAddress();
      /**
       * <code>optional string address = 1;</code>
       */
      com.google.protobuf.ByteString
          getAddressBytes();

      // optional int64 addressId = 2;
      /**
       * <code>optional int64 addressId = 2;</code>
       */
      boolean hasAddressId();
      /**
       * <code>optional int64 addressId = 2;</code>
       */
      long getAddressId();
    }
    /**
     * Protobuf type {@code v6.data.model.OrderDetail.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessage
        implements AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Address defaultInstance;
      public static Address getDefaultInstance() {
        return defaultInstance;
      }

      public Address getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                address_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                addressId_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.company.biz.vo.OrderVo.OrderDetail.Address.class, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder.class);
      }

      public static com.google.protobuf.Parser<Address> PARSER =
          new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string address = 1;
      public static final int ADDRESS_FIELD_NUMBER = 1;
      private java.lang.Object address_;
      /**
       * <code>optional string address = 1;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int64 addressId = 2;
      public static final int ADDRESSID_FIELD_NUMBER = 2;
      private long addressId_;
      /**
       * <code>optional int64 addressId = 2;</code>
       */
      public boolean hasAddressId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 addressId = 2;</code>
       */
      public long getAddressId() {
        return addressId_;
      }

      private void initFields() {
        address_ = "";
        addressId_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getAddressBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, addressId_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getAddressBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, addressId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.company.biz.vo.OrderVo.OrderDetail.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.company.biz.vo.OrderVo.OrderDetail.Address prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code v6.data.model.OrderDetail.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.company.biz.vo.OrderVo.OrderDetail.Address.class, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder.class);
        }

        // Construct using com.company.biz.vo.OrderVo.OrderDetail.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          address_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          addressId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_Address_descriptor;
        }

        public com.company.biz.vo.OrderVo.OrderDetail.Address getDefaultInstanceForType() {
          return com.company.biz.vo.OrderVo.OrderDetail.Address.getDefaultInstance();
        }

        public com.company.biz.vo.OrderVo.OrderDetail.Address build() {
          com.company.biz.vo.OrderVo.OrderDetail.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.company.biz.vo.OrderVo.OrderDetail.Address buildPartial() {
          com.company.biz.vo.OrderVo.OrderDetail.Address result = new com.company.biz.vo.OrderVo.OrderDetail.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.address_ = address_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.addressId_ = addressId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.company.biz.vo.OrderVo.OrderDetail.Address) {
            return mergeFrom((com.company.biz.vo.OrderVo.OrderDetail.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.company.biz.vo.OrderVo.OrderDetail.Address other) {
          if (other == com.company.biz.vo.OrderVo.OrderDetail.Address.getDefaultInstance()) return this;
          if (other.hasAddress()) {
            bitField0_ |= 0x00000001;
            address_ = other.address_;
            onChanged();
          }
          if (other.hasAddressId()) {
            setAddressId(other.getAddressId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.company.biz.vo.OrderVo.OrderDetail.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.company.biz.vo.OrderVo.OrderDetail.Address) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string address = 1;
        private java.lang.Object address_ = "";
        /**
         * <code>optional string address = 1;</code>
         */
        public boolean hasAddress() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public java.lang.String getAddress() {
          java.lang.Object ref = address_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            address_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAddressBytes() {
          java.lang.Object ref = address_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            address_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public Builder setAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          address_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public Builder clearAddress() {
          bitField0_ = (bitField0_ & ~0x00000001);
          address_ = getDefaultInstance().getAddress();
          onChanged();
          return this;
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public Builder setAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          address_ = value;
          onChanged();
          return this;
        }

        // optional int64 addressId = 2;
        private long addressId_ ;
        /**
         * <code>optional int64 addressId = 2;</code>
         */
        public boolean hasAddressId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int64 addressId = 2;</code>
         */
        public long getAddressId() {
          return addressId_;
        }
        /**
         * <code>optional int64 addressId = 2;</code>
         */
        public Builder setAddressId(long value) {
          bitField0_ |= 0x00000002;
          addressId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 addressId = 2;</code>
         */
        public Builder clearAddressId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          addressId_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:v6.data.model.OrderDetail.Address)
      }

      static {
        defaultInstance = new Address(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:v6.data.model.OrderDetail.Address)
    }

    private int bitField0_;
    // required string serialNo = 1;
    public static final int SERIALNO_FIELD_NUMBER = 1;
    private java.lang.Object serialNo_;
    /**
     * <code>required string serialNo = 1;</code>
     */
    public boolean hasSerialNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serialNo = 1;</code>
     */
    public java.lang.String getSerialNo() {
      java.lang.Object ref = serialNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serialNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serialNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNoBytes() {
      java.lang.Object ref = serialNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string orderName = 2;
    public static final int ORDERNAME_FIELD_NUMBER = 2;
    private java.lang.Object orderName_;
    /**
     * <code>optional string orderName = 2;</code>
     */
    public boolean hasOrderName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string orderName = 2;</code>
     */
    public java.lang.String getOrderName() {
      java.lang.Object ref = orderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string orderName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderNameBytes() {
      java.lang.Object ref = orderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .v6.data.model.OrderDetail.Address addressList = 3;
    public static final int ADDRESSLIST_FIELD_NUMBER = 3;
    private java.util.List<com.company.biz.vo.OrderVo.OrderDetail.Address> addressList_;
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    public java.util.List<com.company.biz.vo.OrderVo.OrderDetail.Address> getAddressListList() {
      return addressList_;
    }
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    public java.util.List<? extends com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder> 
        getAddressListOrBuilderList() {
      return addressList_;
    }
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    public int getAddressListCount() {
      return addressList_.size();
    }
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    public com.company.biz.vo.OrderVo.OrderDetail.Address getAddressList(int index) {
      return addressList_.get(index);
    }
    /**
     * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
     */
    public com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder getAddressListOrBuilder(
        int index) {
      return addressList_.get(index);
    }

    // optional double orderPrice = 4;
    public static final int ORDERPRICE_FIELD_NUMBER = 4;
    private double orderPrice_;
    /**
     * <code>optional double orderPrice = 4;</code>
     */
    public boolean hasOrderPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double orderPrice = 4;</code>
     */
    public double getOrderPrice() {
      return orderPrice_;
    }

    private void initFields() {
      serialNo_ = "";
      orderName_ = "";
      addressList_ = java.util.Collections.emptyList();
      orderPrice_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSerialNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSerialNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOrderNameBytes());
      }
      for (int i = 0; i < addressList_.size(); i++) {
        output.writeMessage(3, addressList_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(4, orderPrice_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSerialNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOrderNameBytes());
      }
      for (int i = 0; i < addressList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, addressList_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, orderPrice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.company.biz.vo.OrderVo.OrderDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.company.biz.vo.OrderVo.OrderDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v6.data.model.OrderDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.company.biz.vo.OrderVo.OrderDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.company.biz.vo.OrderVo.OrderDetail.class, com.company.biz.vo.OrderVo.OrderDetail.Builder.class);
      }

      // Construct using com.company.biz.vo.OrderVo.OrderDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serialNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        orderName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (addressListBuilder_ == null) {
          addressList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          addressListBuilder_.clear();
        }
        orderPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.company.biz.vo.OrderVo.internal_static_v6_data_model_OrderDetail_descriptor;
      }

      public com.company.biz.vo.OrderVo.OrderDetail getDefaultInstanceForType() {
        return com.company.biz.vo.OrderVo.OrderDetail.getDefaultInstance();
      }

      public com.company.biz.vo.OrderVo.OrderDetail build() {
        com.company.biz.vo.OrderVo.OrderDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.company.biz.vo.OrderVo.OrderDetail buildPartial() {
        com.company.biz.vo.OrderVo.OrderDetail result = new com.company.biz.vo.OrderVo.OrderDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialNo_ = serialNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.orderName_ = orderName_;
        if (addressListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            addressList_ = java.util.Collections.unmodifiableList(addressList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.addressList_ = addressList_;
        } else {
          result.addressList_ = addressListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.orderPrice_ = orderPrice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.company.biz.vo.OrderVo.OrderDetail) {
          return mergeFrom((com.company.biz.vo.OrderVo.OrderDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.company.biz.vo.OrderVo.OrderDetail other) {
        if (other == com.company.biz.vo.OrderVo.OrderDetail.getDefaultInstance()) return this;
        if (other.hasSerialNo()) {
          bitField0_ |= 0x00000001;
          serialNo_ = other.serialNo_;
          onChanged();
        }
        if (other.hasOrderName()) {
          bitField0_ |= 0x00000002;
          orderName_ = other.orderName_;
          onChanged();
        }
        if (addressListBuilder_ == null) {
          if (!other.addressList_.isEmpty()) {
            if (addressList_.isEmpty()) {
              addressList_ = other.addressList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAddressListIsMutable();
              addressList_.addAll(other.addressList_);
            }
            onChanged();
          }
        } else {
          if (!other.addressList_.isEmpty()) {
            if (addressListBuilder_.isEmpty()) {
              addressListBuilder_.dispose();
              addressListBuilder_ = null;
              addressList_ = other.addressList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              addressListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddressListFieldBuilder() : null;
            } else {
              addressListBuilder_.addAllMessages(other.addressList_);
            }
          }
        }
        if (other.hasOrderPrice()) {
          setOrderPrice(other.getOrderPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSerialNo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.company.biz.vo.OrderVo.OrderDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.company.biz.vo.OrderVo.OrderDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serialNo = 1;
      private java.lang.Object serialNo_ = "";
      /**
       * <code>required string serialNo = 1;</code>
       */
      public boolean hasSerialNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serialNo = 1;</code>
       */
      public java.lang.String getSerialNo() {
        java.lang.Object ref = serialNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serialNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serialNo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSerialNoBytes() {
        java.lang.Object ref = serialNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serialNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serialNo = 1;</code>
       */
      public Builder setSerialNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serialNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serialNo = 1;</code>
       */
      public Builder clearSerialNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNo_ = getDefaultInstance().getSerialNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string serialNo = 1;</code>
       */
      public Builder setSerialNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serialNo_ = value;
        onChanged();
        return this;
      }

      // optional string orderName = 2;
      private java.lang.Object orderName_ = "";
      /**
       * <code>optional string orderName = 2;</code>
       */
      public boolean hasOrderName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string orderName = 2;</code>
       */
      public java.lang.String getOrderName() {
        java.lang.Object ref = orderName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          orderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOrderNameBytes() {
        java.lang.Object ref = orderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderName = 2;</code>
       */
      public Builder setOrderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderName = 2;</code>
       */
      public Builder clearOrderName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        orderName_ = getDefaultInstance().getOrderName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderName = 2;</code>
       */
      public Builder setOrderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderName_ = value;
        onChanged();
        return this;
      }

      // repeated .v6.data.model.OrderDetail.Address addressList = 3;
      private java.util.List<com.company.biz.vo.OrderVo.OrderDetail.Address> addressList_ =
        java.util.Collections.emptyList();
      private void ensureAddressListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          addressList_ = new java.util.ArrayList<com.company.biz.vo.OrderVo.OrderDetail.Address>(addressList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.company.biz.vo.OrderVo.OrderDetail.Address, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder, com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder> addressListBuilder_;

      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public java.util.List<com.company.biz.vo.OrderVo.OrderDetail.Address> getAddressListList() {
        if (addressListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addressList_);
        } else {
          return addressListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public int getAddressListCount() {
        if (addressListBuilder_ == null) {
          return addressList_.size();
        } else {
          return addressListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public com.company.biz.vo.OrderVo.OrderDetail.Address getAddressList(int index) {
        if (addressListBuilder_ == null) {
          return addressList_.get(index);
        } else {
          return addressListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder setAddressList(
          int index, com.company.biz.vo.OrderVo.OrderDetail.Address value) {
        if (addressListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressListIsMutable();
          addressList_.set(index, value);
          onChanged();
        } else {
          addressListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder setAddressList(
          int index, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder builderForValue) {
        if (addressListBuilder_ == null) {
          ensureAddressListIsMutable();
          addressList_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder addAddressList(com.company.biz.vo.OrderVo.OrderDetail.Address value) {
        if (addressListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressListIsMutable();
          addressList_.add(value);
          onChanged();
        } else {
          addressListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder addAddressList(
          int index, com.company.biz.vo.OrderVo.OrderDetail.Address value) {
        if (addressListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressListIsMutable();
          addressList_.add(index, value);
          onChanged();
        } else {
          addressListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder addAddressList(
          com.company.biz.vo.OrderVo.OrderDetail.Address.Builder builderForValue) {
        if (addressListBuilder_ == null) {
          ensureAddressListIsMutable();
          addressList_.add(builderForValue.build());
          onChanged();
        } else {
          addressListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder addAddressList(
          int index, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder builderForValue) {
        if (addressListBuilder_ == null) {
          ensureAddressListIsMutable();
          addressList_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder addAllAddressList(
          java.lang.Iterable<? extends com.company.biz.vo.OrderVo.OrderDetail.Address> values) {
        if (addressListBuilder_ == null) {
          ensureAddressListIsMutable();
          super.addAll(values, addressList_);
          onChanged();
        } else {
          addressListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder clearAddressList() {
        if (addressListBuilder_ == null) {
          addressList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          addressListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public Builder removeAddressList(int index) {
        if (addressListBuilder_ == null) {
          ensureAddressListIsMutable();
          addressList_.remove(index);
          onChanged();
        } else {
          addressListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public com.company.biz.vo.OrderVo.OrderDetail.Address.Builder getAddressListBuilder(
          int index) {
        return getAddressListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder getAddressListOrBuilder(
          int index) {
        if (addressListBuilder_ == null) {
          return addressList_.get(index);  } else {
          return addressListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public java.util.List<? extends com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder> 
           getAddressListOrBuilderList() {
        if (addressListBuilder_ != null) {
          return addressListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addressList_);
        }
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public com.company.biz.vo.OrderVo.OrderDetail.Address.Builder addAddressListBuilder() {
        return getAddressListFieldBuilder().addBuilder(
            com.company.biz.vo.OrderVo.OrderDetail.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public com.company.biz.vo.OrderVo.OrderDetail.Address.Builder addAddressListBuilder(
          int index) {
        return getAddressListFieldBuilder().addBuilder(
            index, com.company.biz.vo.OrderVo.OrderDetail.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .v6.data.model.OrderDetail.Address addressList = 3;</code>
       */
      public java.util.List<com.company.biz.vo.OrderVo.OrderDetail.Address.Builder> 
           getAddressListBuilderList() {
        return getAddressListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.company.biz.vo.OrderVo.OrderDetail.Address, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder, com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder> 
          getAddressListFieldBuilder() {
        if (addressListBuilder_ == null) {
          addressListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.company.biz.vo.OrderVo.OrderDetail.Address, com.company.biz.vo.OrderVo.OrderDetail.Address.Builder, com.company.biz.vo.OrderVo.OrderDetail.AddressOrBuilder>(
                  addressList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          addressList_ = null;
        }
        return addressListBuilder_;
      }

      // optional double orderPrice = 4;
      private double orderPrice_ ;
      /**
       * <code>optional double orderPrice = 4;</code>
       */
      public boolean hasOrderPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double orderPrice = 4;</code>
       */
      public double getOrderPrice() {
        return orderPrice_;
      }
      /**
       * <code>optional double orderPrice = 4;</code>
       */
      public Builder setOrderPrice(double value) {
        bitField0_ |= 0x00000008;
        orderPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double orderPrice = 4;</code>
       */
      public Builder clearOrderPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        orderPrice_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:v6.data.model.OrderDetail)
    }

    static {
      defaultInstance = new OrderDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:v6.data.model.OrderDetail)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_v6_data_model_OrderDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_v6_data_model_OrderDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_v6_data_model_OrderDetail_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_v6_data_model_OrderDetail_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n wyvern/data/model/orderDto.proto\022\rv6.d" +
      "ata.model\"\256\001\n\013OrderDetail\022\020\n\010serialNo\030\001 " +
      "\002(\t\022\021\n\torderName\030\002 \001(\t\0227\n\013addressList\030\003 " +
      "\003(\0132\".v6.data.model.OrderDetail.Address\022" +
      "\022\n\norderPrice\030\004 \001(\001\032-\n\007Address\022\017\n\007addres" +
      "s\030\001 \001(\t\022\021\n\taddressId\030\002 \001(\003B\035\n\022com.compan" +
      "y.biz.voB\007OrderVo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_v6_data_model_OrderDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_v6_data_model_OrderDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_v6_data_model_OrderDetail_descriptor,
              new java.lang.String[] { "SerialNo", "OrderName", "AddressList", "OrderPrice", });
          internal_static_v6_data_model_OrderDetail_Address_descriptor =
            internal_static_v6_data_model_OrderDetail_descriptor.getNestedTypes().get(0);
          internal_static_v6_data_model_OrderDetail_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_v6_data_model_OrderDetail_Address_descriptor,
              new java.lang.String[] { "Address", "AddressId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
